apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: secureboard-api
    newName: secureboard-api
    newTag: k8s-local

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: secureboard-api
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: secureboard-api
      spec:
        template:
          spec:
            initContainers:
              - name: database-migrations
                imagePullPolicy: Never
            containers:
              - name: api
                imagePullPolicy: Never
